name: try loop

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read .env File and Set Build Arguments
        run: |
          echo "${{ secrets.ENV }}" > .env
          source .env
          echo $YOU
