name: try loop

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read .env File and Set Build Arguments
        run: |
          export ENV_CONTENT=${{ vers.ENV }}
          export ENV_STRING=''

          IFS=$'\n'       # Set Internal Field Separator to newline
          for line in $my_secret; do
            echo "Line: $line"
          done
